using Content.Client._Stalker_EN.FactionRelations;
using Content.Shared._Stalker_EN.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// A single message row in a channel or DM view, showing sender, timestamp, content, and a reply button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerMessageEntry : BoxContainer
{
    /// <summary>Raised when the user clicks reply; args are (messageId, snippetPreview).</summary>
    public event Action<uint, string>? OnReply;

    public STMessengerMessageEntry(STMessengerMessage message)
    {
        RobustXamlLoader.Load(this);

        SenderLabel.Text = message.Sender;

        if (message.SenderFaction is not null
            && STFactionPatchIcons.PatchStates.TryGetValue(message.SenderFaction, out var patch))
        {
            var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
            FactionIcon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(patch.Rsi, patch.State));
            FactionIcon.Visible = true;
        }

        var hours = (int)message.Timestamp.TotalHours;
        var minutes = message.Timestamp.Minutes;
        var seconds = message.Timestamp.Seconds;
        TimestampLabel.Text = $"{hours:D2}:{minutes:D2}:{seconds:D2}";

        if (message.ReplySnippet is not null)
        {
            ReplyQuote.Visible = true;
            ReplyQuote.Text = $"> {message.ReplySnippet}";
        }

        ContentLabel.SetMessage(FormattedMessage.FromMarkupPermissive(FormattedMessage.EscapeText(message.Content)));

        var snippet = message.Content.Length > STMessengerChat.MaxReplySnippetLength
            ? message.Content[..STMessengerChat.MaxReplySnippetLength] + "..."
            : message.Content;

        ReplyButton.OnPressed += _ => OnReply?.Invoke(message.Id, snippet);
    }
}
